# Title shown in Application Information tab.
title: Mozilla Hubs Oracle Cloud Launcher
# Sub Title shown in Application Information tab.
name: Deploy-Hubs
description: Create and launch Hubs environments on Oracle Cloud
informationalText: Create Mozilla Hubs Environment
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
source:
  type: marketplace
  reference: 16132843

locale: "en"
variableGroups:
  - title: "Hubs Deployment Parameters"
    variables: 
      - targetCompartment
  - title: "Application Details"
    variables:
      - ${adminEmail}
  - title: "Domain Configuration"
    variables:
      - ${domainName}
      - ${ociHostedDomain}
      - ${internalDomainName}
      - ${shortLinkDomainName}
  - title: "Email Configuration"
    variables:
      - ${outgoingEmailDomain}
      - ${outgoingEmailSubdomainPrefix}
  - title: "Server Configuration"
    variables:
      - ${restrictSiteAccess}
      - ${keyPair}
      - ${numberOfAppServers}
      - ${numberOfStreamingServers}
      - ${appServerInstanceType}
      - ${streamingServerInstanceType}
  - title: "Cost Management"
    variables:
      - ${dbBudget}
      - ${storageLimit}
  - title: "Offline Mode"
    variables:
      - ${stackMode}
      - ${offlineRedirectURL}      
  - title: "Database Configuration"
    variables:
      - ${dbAutoPause}
      - ${dbBackupRetentionPeriod}
      - ${dbAutoScale}
  - title: "Restore from Backup"
    variables: 
      - ${notImplementedYet}
  - title: "Let's Encrypt"
    variables:
      - ${letsEncryptContactEmail}
  - title: "Advanced - Leave these alone unless you know what you are doing!"
    variables: 
      - ${notImplementedYet}
  - title: "Permissions"
    variables:
      - ${iamRole}

	variables:
    # compartmentId dynamic dropdown, targetCompartment present in input variables
  targetCompartment:
    type: oci:identity:compartment:id
    title: "Target Compartment"
    description: "Select an available compartment.  Assets can be moved to other compartments after creation."
    required: true

  adminEmail:
    type: string
    title: "Administration Email Address"
    description: "Email address for you administration account.  Individuals with access to this email address will have full administrative control of your hub.  Before you can log in, you will need to verify this email address - you will get a verification email from Oracle after the stack is ready." 
    required: true

  domainName:
    type: string
    title: "Domain Name"	
    description: "Domain name your hubs will be hosted Oracle. (eg myhub.com or hub.mydomain.com.) This should be a domain you already own, either on a third party provider (eg GoDaddy or Namecheap) or OCI DNS."
    required: true

  ociHostedDomain:
    type: boolean
    title: "Is your domain setup on Oracle DNS?"
    description: "Additional setup required for non-Oracle hosted domains."
    required: true

  internalDomainName:
    type: string
    title: "Internal domain name"
    description: "Your hub needs a domain name to use internally for server management.  If you primary domain is on Oracle DNS and you're not using it for anything else, you can choose it here.  Otherwise you'll need to register a new domainname on OCI DNS for this (for example, myhub-internal.com). This domainname will not be seen by users."
    required: true
  
  shortLinkDomainName:
    type: string
    title: "Short link domain name"	
    description: "You'll need a Oracle domainname for short room permalinks, entry codes, and device linking.  (eg myhub.link)  It should *not* be the same domaina s any of the domain names that you specified above.  This domain will be used by visitors to share room links, and ideally should be short and easy to type since it will be typed by users on mobile devices and in VR."
    required: true

  outgoingEmailDomain:
    type: string
    title: "Outgoing email domain"
    description: "To verify email addresses, your hub needs to be able to send email. If you do not have an existing email SMTP provider, choose a Oracle domain you'd like to send email from. It will be set up automatically using Oracle Email Service. If you have an existing email provider you'd like to send email from (eg Mailchimp) or already have a verified domain in Oracle Email Service select the same zone you chose above for Internal Oracle DNS Zone and you will be able to enter the login credentials from your email provider later."
    default: "mail"
    required: false

  outgoingEmailSubdomainPrefix:
    type: string
    title: "Outgoing email subdomain"
    description: "The Subdomain prefix to use for outgoing emails. For example, if your Outgoing Email Oracle Zone is set to myhub.com, setting this field to (mail) will send email from the domain mail.myhub.com. If you have a third party email provider (eg Mailchimp) you can ignore this field."
    required: false
  
  restrictSiteAccess:
    type: string
    title: "Restrict Site Access"
    description: "You can restrict which IP addresses can access your site. To allow anyone on the Internet to load your site, choose (Allow anyone to access my site)"
    default: "Allow Everyone to access my site"

  keyPair:
    type: oci:core:ssh:publickey
    title: "Key Pair"
    description: "SSH Keypair for server SSH access. If there no keypairs in this list, you will need to add a SSH keypair via the Oracle console. See: https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/managingkeypairs.htm."
    required: true 

  numberOfAppServers:
    type: integer
    title: "Number of Application Servers"
    description: "The number of app server(s) to run. The app servers provide all the necessary services for your hub. You must run at least one app server."
    default: "1"
    required: true

  numberOfStreamingServers:
    type: interger
    title: "Number of voice/videos streaming servers"
    description: "The number of dedicated voice/video streaming server(s) you'd like to run. These servers are optional - enter a zero here if you do not want to run any streaming servers. Adding streaming servers will take network and CPU load off of your app servers. These servers will transmit voice and streaming video data between users."
    default: "0"
    required: false

  appServerInstanceType:
    type: string
    title: "Application Server Instance Type"
    description: "The Oracle compute shape type for your app server(s). Choose a (t) instance type if you expect bursty use of the service, and the (c) types if you expect steady usage."

  streamingServerInstanceType:
    type: string
    title: "Streaming Server Instance Type"
    description: "The Oracle Shape type for your streaming server(s), if you have added any. This field will not be used if you entered zero for the number of streaming servers. Choose a (t) instance type if you expect bursty use of the service, and the (c) types if you expect steady usage."

  dbBudget:
    type: interger
    title: "Account Monthly Database Budget (US dollars, no $ and no cents)"
    description: "If you do not want a monthly database budget, set this to zero. To save costs, your Hubs database will be shut down when nobody is hitting your site. When visitors are using your site, you will incur database costs. To avoid unexpected charges, you can set a monthly budget. If you are running multiple hubs, this budget should reflect your maximum allowed cost across *all* your hubs in this region. This hub will automatically switch into Offline mode if the database charges across all your hubs in this region exceed this budget. A minimum $20 budget is recommended and will provide more than 40 hours a week of connectivity for a hub. You only pay for what you use. Leave this field blank to fall back to your  Max database capacity setting in Database Configuration to limit your database cost. Pricing info can be found at https://www.oracle.com/cloud/compute/pricing/"

  storageLimit:
    type: interger
    title: "Storage Limit (in GB)"
    description: "When users upload scenes, avatars, or files, they will use disk storage. You only pay for the storage you use. You can set a maximum storage amount here (in GB) to ensure there are no unexpected charges. Pricing info can be found at https://www.oracle.com/cloud/storage/pricing/"

  stackMode:
    type: interger
    title: "Stack Mode"
    description: "To save costs, you can switch your stack from being Online to Offline when it is not needed. This will shut down the servers while keeping all of your data. Once your stack is switched back to Online, it will come back up just how you left it."

  offlineRedirectURL:
    type: string
    title: "Offline Redirect URL (Optional)"
    description: "(Optional) When your stack is set to Offline, visitors will be redirected to this URL."

  dbAutoPause:
    type: boolean
    title: "Auto-pause Resources" 
    description: "Your hub uses the Aurora Serverless database, which can greatly save costs by pausing the database when your hub is not in use. However, when the database is paused, it can take up to 20 seconds for your site to come back up when you visit it. You can turn off database pausing if you'd like to avoid any delay in loading your site. Turning off pausing will incur continuous hourly database costs. Pricing info can be found at https://aws.amazon.com/rds/aurora/serverless/"

  dbBackupRetentionPeriod:
    type: interger
    title: "Database backup retention period (in days)"
    description: "Number of days your database backups will be retained for."

  dbAutoScale:
    type: boolean 
    title: "Autoscale Resources"
    description: "Allow Database and other resources to scale as needed"

  letsEncryptContactEmail:
    type: string
    title: "Let's Encrypt Contact Email Address (Optional)"
    description: "Your servers will use Let's Encrypt to automatically manage SSL certificates. To receive urgent email notifications regarding your certificates from Let's Encrypt, specify a contact email here. This field is optional. By deploying this stack you agree to the LetsEncrypt TOS. (https://letsencrypt.org/repository/)" 
    required: false
  
  iamRole:
    type: string
    title: "IAM Role (optional) Choose the IAM role for CloudFormation to use for all operations performed on the stack."
    description: "Choose an IAM role to explicitly define how CloudFormation can create, modify, or delete resources in the stack. If you don't choose a role, CloudFormation uses permissions based on your user credentials.Learn more "
    required: false

  notImplementedYet:
    type: string
    title: "Feature Not Implemented"
    description: "This feature is pending"

  

# Used to present outputs with more refinement on the Application Information tab.
# The Application Information tab is only shown if the schema has a "title",
# "description", and at least one output in this "outputs" section.
#
# type:
#   - boolean
#   - string
#   - number
#   - link - contains url that can be hyperlinked.  If type is not specified and the
#            value is a proper url, this type is assumed.
#   - ocid - contains an OCID.  An attempt is made to hyperlink it to the designated
#            resource in the console.
#   - csv - synonym for list.  Array of values converted to a comma separated list.
#   - json - synonym for map.  Map of key / values converted to JSON.
#   - list - array of values converted to a comma separated list.
#   - map - map of key / values converted to JSON.
#
# displayText: used in links to give text displayed instead of value
# title: friendly label
# visible: if false, this ouptut is not shown in the outputs section of Application Information.
#          It can still be used as the primaryOutputButton.
outputs:
  controlCenterUrl:
    type: link
    title: Control Center
    displayText: Control Center
    visible: false

  schemaRegistryUrl:
    type: link
    title: Schema Registry
    displayText: Schema Registry

  schemaRegistryPublicIps:
    type: csv
    title: Public IPs

  schemaRegistryLoadBalancer:
    type: ocid
    title: Load Balancer

  brokerPublicIps:
    type: csv

  connectUrl:
    type: link
    title: Connect
    displayText: Connect

  connectPublicIps:
    type: csv
    title: Public IPs

  restUrl:
    type: link
    title: Rest API

# primaryOutputButton is a reference to a link output that creates a primary button
# on the Application Information tab.
# (Optional) if not provided, no primary button is shown.  Also if the output
# referenced is not a link output, no button is shown.
primaryOutputButton: ${controlCenterUrl}

# Used to group Outputs.  Any outputs not included in these defined groups, are
# included in a default group labelled "Outputs".
# (Optional) if not groups are given, outputs are not grouped at all.
outputGroups:
  - title: Schema Registry
    outputs:
      - ${schemaRegistryUrl}
      - ${schemaRegistryPublicIps}
      - ${schemaRegistryInstances}
      - ${schemaRegistryLoadBalancer}

  - title: Broker / Connect
    outputs:
      - ${brokerPublicIps}
      - ${brokerInstances}
      - ${connectUrl}
      - ${connectPublicIps}
      - ${restUrl}